# Generated by Django 4.2.7 on 2025-09-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок контента', max_length=255, verbose_name='Заголовок')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Автоматически увеличивается при просмотре страницы', verbose_name='Счетчик просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('text_content', models.TextField(help_text='Текст произвольной длины, связанный с аудио', verbose_name='Текстовое содержимое')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('video_file_url', models.URLField(help_text='URL видеофайла', verbose_name='Ссылка на видеофайл')),
                ('subtitle_file_url', models.URLField(blank=True, help_text='URL файла субтитров (опционально)', null=True, verbose_name='Ссылка на файл субтитров')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
            bases=('content.content',),
        ),
    ]
